services:
  db:
    container_name: postgres-services
    image: postgres:15.1
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=12345678
    restart: always
    networks:
      red_interna:
        ipv4_address: 172.16.10.20

  pgADmin:
    depends_on:
      - db
    container_name: pgadmin
    image: dpage/pgadmin4:6.17
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_PASSWORD=123456
      - PGADMIN_DEFAULT_EMAIL=tulyrisquet@gmail.com
    restart: always
    networks:
      red_interna:
        ipv4_address: 172.16.10.25

  app:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: dockerfile
    volumes:
      - static:/app/static
      - ./:/app
    networks:
      red_interna:
        ipv4_address: 172.16.10.30

  nginx:
    depends_on:
      - app
    image: nginx:1.13
    ports:
      - "8000:80"
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/app/static
    networks:
      red_interna:
        ipv4_address: 172.16.10.45

networks:
  red_interna:
    ipam:
      config:
        - subnet: 172.16.10.0/24

volumes:
  postgres_db:
  static:
