# Generated by Django 4.2.6 on 2024-03-04 06:21

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buoy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('lat', models.FloatField(verbose_name='Latitud')),
                ('lon', models.FloatField(verbose_name='Longitud')),
                ('img', models.ImageField(blank=True, null=True, upload_to='static/buoys', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Boya',
                'verbose_name_plural': 'Boyas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('fullname', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('min', models.FloatField(blank=True, null=True, verbose_name='Min')),
                ('max', models.FloatField(blank=True, null=True, verbose_name='Max')),
                ('uom', models.CharField(max_length=100, verbose_name='Unidad de medida')),
            ],
            options={
                'verbose_name': 'Parámetro',
                'verbose_name_plural': 'Parámetros',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UploadDataJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('current', models.IntegerField()),
                ('total', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('buoy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.buoy')),
            ],
            options={
                'verbose_name': 'Carga',
                'verbose_name_plural': 'Cargas',
            },
        ),
        migrations.AddField(
            model_name='buoy',
            name='parameters',
            field=models.ManyToManyField(blank=True, to='api.parameter', verbose_name='Parámetros'),
        ),
        migrations.CreateModel(
            name='ActionItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('error', models.TextField()),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('buoy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.buoy')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parameter')),
            ],
            options={
                'verbose_name': 'Acción',
                'verbose_name_plural': 'Acciones',
                'ordering': ['buoy_id', 'parameter_id', 'timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Nombre de Usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('first_name', models.CharField(max_length=128, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=128, verbose_name='Apellidos')),
                ('company', models.CharField(blank=True, max_length=128, null=True, verbose_name='Puesto Laboral')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('timestamp', models.BigIntegerField()),
                ('buoy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.buoy')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parameter')),
            ],
            options={
                'verbose_name': 'Dato',
                'verbose_name_plural': 'Datos',
                'unique_together': {('buoy_id', 'parameter_id', 'timestamp')},
            },
        ),
    ]
