# Generated by Django 4.2.6 on 2024-03-18 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_applicationuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='buoy',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
