# Generated by Django 4.2.6 on 2024-04-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_buoy_active_parameter_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='errors',
            field=models.TextField(blank=True, null=True),
        ),
    ]
