# Generated by Django 4.2.6 on 2024-04-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_data_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='buoy',
            name='depth',
            field=models.FloatField(blank=True, null=True, verbose_name='Profundidad'),
        ),
        migrations.AddField(
            model_name='buoy',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fabricante'),
        ),
        migrations.AddField(
            model_name='buoy',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo'),
        ),
    ]
