# Generated by Django 4.2.6 on 2024-04-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_buoy_depth_buoy_manufacturer_buoy_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='buoy',
            name='gsm',
            field=models.BooleanField(default=False, verbose_name='Coordenadas GSM'),
        ),
    ]
