# Generated by Django 4.2.6 on 2024-04-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_buoy_gsm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buoy',
            name='lat',
            field=models.CharField(verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='buoy',
            name='lon',
            field=models.CharField(verbose_name='Longitud'),
        ),
    ]
