# Generated by Django 4.2.6 on 2024-05-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_buoy_lat_alter_buoy_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='buoy',
            name='plans',
            field=models.ImageField(blank=True, null=True, upload_to='static/buoys', verbose_name='Planos de Instalación'),
        ),
    ]
