# Generated by Django 5.0.1 on 2024-05-13 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_buoy_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='buoy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.buoy', verbose_name='Boya'),
        ),
        migrations.AlterField(
            model_name='data',
            name='errors',
            field=models.TextField(blank=True, null=True, verbose_name='Errores'),
        ),
        migrations.AlterField(
            model_name='data',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parameter', verbose_name='Parámetro'),
        ),
        migrations.AlterField(
            model_name='data',
            name='timestamp',
            field=models.BigIntegerField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='data',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor'),
        ),
    ]
