# Generated by Django 5.0.1 on 2024-05-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_data_buoy_alter_data_errors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationuser',
            name='company',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Empresa'),
        ),
    ]
