# Generated by Django 4.2.6 on 2024-06-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_applicationuser_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('img', models.ImageField(blank=True, null=True, upload_to='static/news', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='applicationuser',
            name='company',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Entidad'),
        ),
    ]
